package nntc.tsvetkova.myapp;

import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.image.Image;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.Objects;
import java.util.prefs.Preferences;


public class DatabaseManager {
    private static String URL;
    private static String USER;
    private static String PASSWORD;
    private static String SCHEMA;

    private Preferences prefs;

    private Connection connection;

    // конструктор
    // создали для инициализации prefs на уровне всего класса
    public DatabaseManager() {
        prefs = Preferences.userNodeForPackage(DesktopApplication.class);
    }

    // Метод для подключения к базе данных
    public void connect() throws SQLException {

        URL = String.format(
                "jdbc:postgresql://%s:%s/%s?currentSchema=%s",
                prefs.get("subdAddress", "localhost"),
                prefs.get("subdPort", "5432"),
                prefs.get("subdDbname", "postgres"),
                prefs.get("subdSchema", "public")
        );
        USER = prefs.get("subdUser", "postgres");
        PASSWORD = prefs.get("subdPassword", "postgres");
        SCHEMA = prefs.get("subdSchema", "public");

        connection = DriverManager.getConnection(URL, USER, PASSWORD);
        System.out.println("Успешно подключено к базе данных.");
    }

    // Метод для отключения от базы данных
    public void disconnect() {
        if (connection != null) {
            try {
                connection.close();
                System.out.println("Соединение с базой данных закрыто.");
            } catch (SQLException e) {
                System.out.println("Ошибка при закрытии соединения: " + e.getMessage());
                // Показываем модальное окно с ошибкой
                Platform.runLater(() -> ErrorDialog.showError("Ошибка при закрытии соединения: ", e.getMessage()));
            }
        }
    }

    // Метод развёртывания таблиц базы данных
    public void ensureTablesExists() {
        String ddlQueries = String.format("""
    CREATE TABLE IF NOT EXISTS %s.service (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar NOT NULL,
    description varchar NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT service_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS %s.products (
    id int GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" varchar NULL,
    price numeric(10, 2) NOT NULL,
    description varchar NULL,
    image_data bytea NULL,
    CONSTRAINT products_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS %s.worker (
    id int GENERATED ALWAYS AS IDENTITY NOT NULL,
    "name" varchar NOT NULL,
    email varchar NOT NULL,
    CONSTRAINT worker_pk PRIMARY KEY (id),
    CONSTRAINT worker_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS %s."user" (
    id SERIAL PRIMARY KEY,
    "name" varchar NULL,
    email varchar NOT NULL,
    password varchar NOT NULL,
    role varchar NOT NULL CHECK (role IN ('admin', 'customer')),
    CONSTRAINT user_uniqueEmail UNIQUE (email),
    CONSTRAINT user_uniquePass UNIQUE (password)
);

CREATE TABLE IF NOT EXISTS %s."order" (
    id int GENERATED ALWAYS AS IDENTITY NOT NULL,
    "time" varchar NOT NULL,
    "date" varchar NOT NULL,
    worker int NULL,
    "user" int NULL,
    service int NULL,
    products int NULL,
    CONSTRAINT order_pk PRIMARY KEY (id),
    CONSTRAINT order_user_fk FOREIGN KEY ("user") REFERENCES %s."user"(id),
    CONSTRAINT order_service_fk FOREIGN KEY (service) REFERENCES %s.service(id) ON DELETE RESTRICT,
    CONSTRAINT order_storage_fk FOREIGN KEY (products) REFERENCES %s.products(id) ON DELETE SET NULL,
    CONSTRAINT order_worker_fk FOREIGN KEY (worker) REFERENCES %s.worker(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS %s.order_product (
    order_id int4 NOT NULL,
    product_id int4 NOT NULL,
    CONSTRAINT order_product_pk PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES %s.products(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES %s."order"(id) ON DELETE CASCADE ON UPDATE CASCADE
);""", SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA, SCHEMA);


        try (Statement statement = connection.createStatement()) {
            statement.execute(ddlQueries);// Если нужно, то можно и DML запросы здесь запустить
            System.out.println("Проверка структуры базы данных завершена.");
        } catch (SQLException e) {
            System.out.println("Ошибка при проверке/создании таблицы: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при проверке/создании таблицы: ", e.getMessage()));
        }
    }

    public void ensureAdminExists() {
        String query = "INSERT INTO admin (name, email, password) VALUES ('admin', 'admin', 'admin') ON CONFLICT DO NOTHING";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    public User authenticateUser(String name, String email, String password, String role) {
        String query = "SELECT * FROM \"user\" WHERE \"name\" = ? AND email = ? AND password = ? AND role = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, name); // Используем переменную name
            statement.setString(2, email);
            statement.setString(3, password);
            statement.setString(4, role);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                return new User(resultSet.getInt("id"), resultSet.getString("name"), email, password, role);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }



    public boolean registerUser(String name, String email, String password, String role) {
        String checkQuery = "SELECT COUNT(*) FROM \"user\" WHERE email = ?";
        String query = "INSERT INTO \"user\" (\"name\", email, password, role) VALUES (?, ?, ?, ?)";
        try (PreparedStatement checkStatement = connection.prepareStatement(checkQuery)) {
            checkStatement.setString(1, email);
            ResultSet rs = checkStatement.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                System.out.println("Ошибка: пользователь с таким email уже существует.");
                return false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, name);
            statement.setString(2, email);
            statement.setString(3, password);
            statement.setString(4, role);
            statement.executeUpdate();
            return true;
        } catch (SQLException e) {
            if (e.getMessage().contains("duplicate key")) {
                System.out.println("Ошибка: пользователь с таким логином уже существует.");
            } else {
                e.printStackTrace();
            }
        }
        return false;
    }


    public void productsInsertData(String name, Float price) {
        String query = String.format("INSERT INTO %s (name, price) VALUES ('%s', %s)", SCHEMA.concat(".products"), name, String.format("%f", price).replace(",", "."));
        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsInserted = preparedStatement.executeUpdate();
            System.out.println("Добавлено строк: " + rowsInserted);
        } catch (SQLException e) {
            System.out.println("Ошибка при вставке данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при вставке данных: ", e.getMessage()));
        }
    }

    public void productsUpdateData(Integer id, String name, float price) {
        String query = String.format("UPDATE %s SET name='%s', price=%s WHERE id=%d", SCHEMA.concat(".products"), name, String.format("%f", price).replace(",", "."), id);

        System.out.println("QUERY:");
        System.out.println(query);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsUpdated = preparedStatement.executeUpdate();
            System.out.println("Обновлено строк: " + rowsUpdated);
        } catch (SQLException e) {
            System.out.println("Ошибка при изменении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при изменении данных: ", e.getMessage()));
        }
    }

    public void productsDeleteData(int id) {
        String query = String.format("DELETE FROM %s WHERE id=%d", SCHEMA.concat(".products"), id);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsDeleted = preparedStatement.executeUpdate();
            System.out.println("Удалено строк: " + rowsDeleted);
        } catch (SQLException e) {
            System.out.println("Ошибка при удалении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении данных: ", e.getMessage()));
        }
    }

    // Пример: Получение данных
    public ObservableList<Product> productsFetchData() {

        ObservableList<Product> re = FXCollections.observableArrayList();
        String query = String.format("SELECT id, name, price FROM %s", SCHEMA.concat(".products"));

        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {

            while (resultSet.next()) {
                re.add(new Product(resultSet.getInt("id"), resultSet.getString("name"), resultSet.getFloat("price")));
            }

        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public ObservableList<ProductInOrder> productsFetchDataInOrder(int id) {
        ObservableList<ProductInOrder> re = FXCollections.observableArrayList();

        String query = String.format(
                "SELECT products.id AS id, products.name AS name, products.price AS price " +
                        "FROM %s.products " +
                        "INNER JOIN %s.order ON 'order'.products = products.id " +
                        "WHERE 'order'.id = %d ORDER BY products.id;",
                SCHEMA.concat(".products"),
                SCHEMA.concat(".order_product"), id);

        //System.out.println("QUERY: ".concat(query));

        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, id); // Устанавливаем параметр id

            try (var resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    re.add(new ProductInOrder(
                            resultSet.getInt("id"),
                            resultSet.getString("name"),
                            resultSet.getFloat("price")
                    ));
                }
            }

        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public void customersInsertData(String name, String email) {
        String query = String.format("INSERT INTO %s (name, email) VALUES ('%s', '%s') WHERE role = 'customer'", SCHEMA.concat(".user"), name, email);
        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsInserted = preparedStatement.executeUpdate();
            System.out.println("Добавлено строк: " + rowsInserted);
        } catch (SQLException e) {
            System.out.println("Ошибка при вставке данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при вставке данных: ", e.getMessage()));
        }
    }

    public void customersUpdateData(Integer id, String name, String email) {
        String query = String.format("UPDATE %s SET name='%s', email='%s' WHERE id=%d AND role = 'customer'", SCHEMA.concat(".user"), name, email, id);

        //System.out.println("QUERY:" + query);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsUpdated = preparedStatement.executeUpdate();
            System.out.println("Обновлено строк: " + rowsUpdated);
        } catch (SQLException e) {
            System.out.println("Ошибка при изменении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при изменении данных: ", e.getMessage()));
        }
    }

    public void customersDeleteData(int id) {
        String query = String.format("DELETE FROM %s WHERE id=%d AND role = 'customer'", SCHEMA.concat(".user"), id);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsDeleted = preparedStatement.executeUpdate();
            System.out.println("Удалено строк: " + rowsDeleted);
        } catch (SQLException e) {
            System.out.println("Ошибка при удалении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении данных: ", e.getMessage()));
        }
    }

    // Пример: Получение данных
    public ObservableList<User> customersFetchData() {

        ObservableList<User> re = FXCollections.observableArrayList();
        String query = String.format("SELECT id, name, email FROM %s WHERE role = 'customer'", SCHEMA.concat(".user"));

        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {
            while (resultSet.next()) {
                re.add(new User(resultSet.getInt("id"), resultSet.getString("name"),
                        resultSet.getString("email"), resultSet.getString("password"),
                        resultSet.getString("role")));
            }
        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public void workerInsertData(String name, String email) {
        String query = String.format("INSERT INTO %s (name, email) VALUES ('%s', '%s')", SCHEMA.concat(".worker"), name, email);
        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsInserted = preparedStatement.executeUpdate();
            System.out.println("Добавлено строк: " + rowsInserted);
        } catch (SQLException e) {
            System.out.println("Ошибка при вставке данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при вставке данных: ", e.getMessage()));
        }
    }

    public void workerUpdateData(Integer id, String name, String email) {
        String query = String.format("UPDATE %s SET name='%s', email=%s WHERE id=%d", SCHEMA.concat(".worker"), name, email, id);

        System.out.println("QUERY:");
        System.out.println(query);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsUpdated = preparedStatement.executeUpdate();
            System.out.println("Обновлено строк: " + rowsUpdated);
        } catch (SQLException e) {
            System.out.println("Ошибка при изменении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при изменении данных: ", e.getMessage()));
        }
    }

    public void workerDeleteData(int id) {
        String query = String.format("DELETE FROM %s WHERE id=%d", SCHEMA.concat(".worker"), id);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsDeleted = preparedStatement.executeUpdate();
            System.out.println("Удалено строк: " + rowsDeleted);
        } catch (SQLException e) {
            System.out.println("Ошибка при удалении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении данных: ", e.getMessage()));
        }
    }

    public ObservableList<Worker> workerFetchData() {

        ObservableList<Worker> re = FXCollections.observableArrayList();
        String query = String.format("SELECT id, name, email FROM %s", SCHEMA.concat(".worker"));
        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {
            while (resultSet.next()) {
                re.add(new Worker(resultSet.getInt("id"), resultSet.getString("name"), resultSet.getString("email")));
            }
        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public boolean saveProductImage(File file, int productId) {
        String query = "UPDATE " + SCHEMA.concat(".products") + " SET image_data = ? WHERE id = ?";
        try (
                InputStream inputStream = new FileInputStream(file);
                var preparedStatement = connection.prepareStatement(query)
        ) {
            preparedStatement.setBinaryStream(1, inputStream, (int) file.length());
            preparedStatement.setInt(2, productId);
            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;
        } catch (Exception e) {
            System.out.println("Ошибка при обновлении изображения: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при обновлении изображения: ", e.getMessage()));
        }
        return false;
    }

    public Image getProductImage(int productId) {
        String query = "SELECT image_data FROM " + SCHEMA.concat(".products") + " WHERE id = ?";
        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, productId);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                InputStream inputStream = resultSet.getBinaryStream("image_data");
                if (inputStream != null) {
                    return new Image(inputStream);
                }
            }
        } catch (Exception e) {
            System.out.println("Ошибка при получении изображения: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при получении изображения: ", e.getMessage()));
        }
        InputStream defaultImageStream = getClass().getResourceAsStream("/noimage.jpg");
        return new Image(Objects.requireNonNull(defaultImageStream));
    }

    public void serviceInsertData(String name, float price) {
        String query = String.format("INSERT INTO %s (\"name\", price) VALUES ('%s', '%s')", SCHEMA.concat(".service"), "name", price);
        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsInserted = preparedStatement.executeUpdate();
            System.out.println("Добавлено строк: " + rowsInserted);
        } catch (SQLException e) {
            System.out.println("Ошибка при вставке данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при вставке данных: ", e.getMessage()));
        }
    }

    public void serviceUpdateData(Integer id, String name, float price) {
        String query = String.format("UPDATE %s SET \"name\"='%s', price=%s WHERE id=%d", SCHEMA.concat(".service"), id, "name", price);

        //System.out.println("QUERY:");
        //System.out.println(query);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsUpdated = preparedStatement.executeUpdate();
            System.out.println("Обновлено строк: " + rowsUpdated);
        } catch (SQLException e) {
            System.out.println("Ошибка при изменении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при изменении данных: ", e.getMessage()));
        }
    }

    public void serviceDeleteData(int id) {
        String query = String.format("DELETE FROM %s WHERE id=%d", SCHEMA.concat(".service"), id);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsDeleted = preparedStatement.executeUpdate();
            System.out.println("Удалено строк: " + rowsDeleted);
        } catch (SQLException e) {
            System.out.println("Ошибка при удалении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении данных: ", e.getMessage()));
        }
    }

    public ObservableList<Service> serviceFetchData() {

        ObservableList<Service> re = FXCollections.observableArrayList();
        String query = String.format("SELECT id, \"name\", email FROM %s", SCHEMA.concat(".service"));
        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {
            while (resultSet.next()) {
                re.add(new Service(resultSet.getInt("id"), resultSet.getString("name"),
                        resultSet.getFloat("price")));
            }
        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }


    public ObservableList<Order> orderFetchData() {

        ObservableList<Order> re = FXCollections.observableArrayList();
        String query = String.format(
                "SELECT o.time AS time, o.date AS date, w.name AS worker_name, " +
                        "u.name AS customer, s.name AS service, p.name AS product " +
                        "FROM %s o " +
                        "LEFT JOIN %s u ON u.id = o.user " +
                        "LEFT JOIN %s w ON w.id = o.worker " +
                        "LEFT JOIN %s s ON s.id = o.service " +
                        "LEFT JOIN %s p ON p.id = o.products " +
                        "WHERE u.role = 'customer'" +
                        "ORDER BY o.date DESC;",
                SCHEMA.concat(".order"),
                SCHEMA.concat(".user"),
                SCHEMA.concat(".worker"),
                SCHEMA.concat(".service"),
                SCHEMA.concat(".products")
        );

        System.out.println("QUERY orderFetchData:" + query);

        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {

            while (resultSet.next()) {
                re.add(new Order(resultSet.getInt("id"), resultSet.getString("date"),
                        resultSet.getString("time"), resultSet.getString("worker"),
                        resultSet.getString("customer"), resultSet.getString("service"),
                        resultSet.getString("products")));
            }

        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public ObservableList<KeyValue> customersGetList() {
        ObservableList<KeyValue> re = FXCollections.observableArrayList();

        String query = String.format("SELECT id, name, email FROM %s WHERE role = 'customer'", SCHEMA.concat(".user"));

        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {

            while (resultSet.next()) {
                re.add(new KeyValue(resultSet.getInt("id"), resultSet.getString("name")));
            }

        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

    public void orderInsertData() {
        // FIXME: реализовать потом
    }

    public void orderUpdateData() {
        // FIXME: реализовать потом
    }

    public void orderDeleteData(int id) {
        String query = String.format("DELETE FROM %s WHERE id=%d", SCHEMA.concat(".orders"), id);

        try (var preparedStatement = connection.prepareStatement(query)) {
            int rowsDeleted = preparedStatement.executeUpdate();
            System.out.println("Удалено строк: " + rowsDeleted);
        } catch (SQLException e) {
            System.out.println("Ошибка при удалении данных: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении данных: ", e.getMessage()));
        }
    }

    public Order getOrderById(int orderEditId) {
        Order re = null;
        String query = String.format("SELECT o.id, o.customer, o.date " +
                        "FROM %s o " +
                        "JOIN %s.user ON o.user = user.id" +
                        "WHERE id = % AND u.role = 'customer'",
                SCHEMA.concat(".orders"),
                SCHEMA.concat(".user"),
                orderEditId);

        try (var preparedStatement = connection.prepareStatement(query);
             var resultSet = preparedStatement.executeQuery()) {
            resultSet.next();
            re = (new Order(resultSet.getInt("id"), resultSet.getString("service"),
                    resultSet.getString("customers"), resultSet.getString("worker"),
                    resultSet.getString("products"), resultSet.getString("date"),
                    resultSet.getString("time")));
            re.setUser(resultSet.getInt("customer"));
            return re;
        } catch (SQLException e) {
            System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
            // Показываем модальное окно с ошибкой
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
        }
        return re;
    }

   public boolean addProductToOrder(int orderId, int productId) {
        String query = "INSERT INTO " + SCHEMA.concat(".order_product") +
                " (order_id, product) VALUES (?, ?)";

        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, orderId);
            preparedStatement.setInt(2, productId);
            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;
       } catch (SQLException e) {
            System.err.println("Ошибка при добавлении: " + e.getMessage());
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при добавлении товара в заказ", e.getMessage()));
            return false;
        }
    }

    public boolean removeProductFromOrder(int orderId, int productId) {
        String query = "DELETE FROM " + SCHEMA.concat(".order_product") +
                " WHERE order_id = ? AND product_id = ?";
        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, orderId);
            preparedStatement.setInt(2, productId);
            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;
        } catch (SQLException e) {
            System.err.println("Ошибка при удалении: " + e.getMessage());
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении: ", e.getMessage()));
            return false;
        }
    }

    public boolean changeCustomerInOrder(int orderId, KeyValue user) {
        String query = "UPDATE " + SCHEMA.concat(".orders") +
                " SET user = ? WHERE id = ? AND role = 'customer'";
        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, user.getKey());
            preparedStatement.setInt(2, orderId);
            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;
        } catch (SQLException e) {
            System.err.println("Ошибка при удалении: " + e.getMessage());
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении: ", e.getMessage()));
            return false;
        }
    }

        public Order createAndGetNewOrder() {
        String queryInsert = "INSERT INTO " + SCHEMA.concat(".orders") +
                " DEFAULT VALUES";
        try (var preparedStatementInsert = connection.prepareStatement(queryInsert)) {
            int affectedRows = preparedStatementInsert.executeUpdate();
            if(affectedRows > 0) {
                String query = String.format("SELECT * " +
                        "FROM %s o " +
                        "ORDER BY o.id DESC LIMIT 1", SCHEMA.concat(".orders"));

                try (var preparedStatement = connection.prepareStatement(query);
                     var resultSet = preparedStatement.executeQuery()) {
                    resultSet.next();
                    Order re = new Order(resultSet.getInt("id"), resultSet.getString("service"),
                            resultSet.getString("customers"), resultSet.getString("worker"),
                            resultSet.getString("products"), resultSet.getString("date"),
                            resultSet.getString("time"));
                    return re;
                } catch (SQLException e) {
                    System.out.println("Ошибка при выполнении запроса: " + e.getMessage());
                    // Показываем модальное окно с ошибкой
                    Platform.runLater(() -> ErrorDialog.showError("Ошибка при выполнении запроса: ", e.getMessage()));
                    return null;
                }
            }
        } catch (SQLException e) {
            System.err.println("Ошибка при удалении: " + e.getMessage());
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении: ", e.getMessage()));
            return null;
        }
        return null;
    }

    public boolean changeWorkerInOrder(int orderId, KeyValue worker) {
        String query = "UPDATE " + SCHEMA.concat(".orders") +
                " SET worker = ? WHERE id = ?";
        try (var preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, worker.getKey());
            preparedStatement.setInt(2, orderId);
            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;
        } catch (SQLException e) {
            System.err.println("Ошибка при удалении: " + e.getMessage());
            Platform.runLater(() -> ErrorDialog.showError("Ошибка при удалении: ", e.getMessage()));
            return false;
        }
    }

}
